nav:
  mainMenu:
    title: ray34g.com
header:
  brand:
    label: ray34g.com
    alt: ray34g.com
    homeURL: https://www.ray34g.com/
search:
  sources:
  - id: www
    baseURL: https://www.ray34g.com
  - id: blog
    baseURL: https://blog.ray34g.com
feed:
  sections:
  - posts
  limit: 20
